from enum import Enum

class Result_Animal_Type(Enum):
    TYPE_CAT = 0
    TYPE_DOG = 1
    TYPE_MONKEY = 2
    TYPE_HORSE = 3
    TYPE_SHEEP = 4
    TYPE_BULL = 5
    TYPE_CHICKEN = 6
    TYPE_PIG = 7
    TYPE_RABBIT = 8
    TYPE_SNAKE = 9


    
    TYPE_EAGLE = 19
    TYPE_CROCODILE = 20
    TYPE_RHINOCEROS = 21
    TYPE_GORILLA = 22
    TYPE_TURTLE = 23
    TYPE_BEAR = 24
    TYPE_DOLPHIN = 25
    TYPE_ELEPHANT = 26
    TYPE_GIRAFFE = 27
    TYPE_LION = 28
    TYPE_TIGER = 29
    TYPE_WHALE = 30
    TYPE_PANDA = 31
    NUM_RESULT_ANIMAL_TYPE = 32

